# Generated by Django 5.2.17 on 2026-10-05 23:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacion', '0037_lavadotanque_trazabilidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('nit', models.CharField(blank=True, db_index=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado')], default='BORRADOR', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_inventario', to='operacion.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_inventario_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=80)),
                ('fecha_factura', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada')], default='BORRADOR', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_inventario_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='inventario.proveedor')),
            ],
            options={
                'ordering': ['-fecha_factura', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida', models.CharField(default='UNID', max_length=30)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('precio_referencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor unitario antes del descuento del proveedor.', max_digits=14)),
                ('costo_neto_ultimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo real pagado después del descuento.', max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('accesorio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='producto_inventario', to='operacion.accesorio')),
            ],
            options={
                'verbose_name': 'Producto de inventario',
                'verbose_name_plural': 'Productos de inventario',
                'ordering': ['accesorio__descripcion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleConsumoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_referencia_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.consumoinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_consumo', to='inventario.productoinventario')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=80)),
                ('descripcion_proveedor', models.CharField(blank=True, max_length=250)),
                ('activa', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_proveedor', to='inventario.productoinventario')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_productos', to='inventario.proveedor')),
            ],
            options={
                'ordering': ['proveedor__nombre', 'codigo_proveedor'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_unitario_lista', models.DecimalField(decimal_places=2, max_digits=14)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.entradainventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_entrada', to='inventario.productoinventario')),
                ('referencia_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_entrada', to='inventario.referenciaproveedor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('BODEGA', 'Bodega'), ('TECNICO', 'En poder de técnico')], db_index=True, max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('tecnico', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicacion_inventario', to='operacion.tecnico')),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALDO_INICIAL', 'Saldo inicial'), ('ENTRADA_COMPRA', 'Entrada por compra'), ('TRASLADO', 'Traslado'), ('CONSUMO', 'Consumo en cliente'), ('DEVOLUCION', 'Devolución'), ('AJUSTE_ENTRADA', 'Ajuste de entrada'), ('AJUSTE_SALIDA', 'Ajuste de salida')], db_index=True, max_length=25)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_referencia_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('costo_neto_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('clave_idempotencia', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='operacion.cliente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario_registrados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.productoinventario')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='inventario.ubicacioninventario')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='inventario.ubicacioninventario')),
            ],
            options={
                'ordering': ['-creado', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExistenciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventario.productoinventario')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventario.ubicacioninventario')),
            ],
            options={
                'ordering': ['producto__accesorio__descripcion'],
            },
        ),
        migrations.AddField(
            model_name='consumoinventario',
            name='ubicacion_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='inventario.ubicacioninventario'),
        ),
        migrations.AddConstraint(
            model_name='entradainventario',
            constraint=models.UniqueConstraint(fields=('proveedor', 'numero_factura'), name='inventario_factura_unica_por_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='referenciaproveedor',
            constraint=models.UniqueConstraint(fields=('proveedor', 'codigo_proveedor'), name='inventario_ref_proveedor_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='existenciainventario',
            constraint=models.UniqueConstraint(fields=('producto', 'ubicacion'), name='inventario_existencia_producto_ubicacion_unica'),
        ),
        migrations.AddConstraint(
            model_name='existenciainventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='inventario_existencia_no_negativa'),
        ),
    ]
