# Generated by Django 6.0.3 on 2026-07-28 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacion', '0015_equipounidad_anio_fabricacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('INFORME', 'Informe Técnico'), ('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Mantenimiento Correctivo'), ('LAVADO', 'Lavado de Tanques'), ('CERTIFICADO', 'Certificado'), ('COTIZACION', 'Cotización'), ('MANUAL', 'Manual'), ('OTRO', 'Otro')], default='INFORME', max_length=20)),
                ('fecha_documento', models.DateField()),
                ('archivo', models.FileField(upload_to='documentos_clientes/%Y/%m/')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En revisión'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='operacion.cliente')),
            ],
            options={
                'ordering': ['-fecha_documento'],
            },
        ),
    ]
