# Generated by Django 6.0.3 on 2026-03-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono_porteria', models.CharField(max_length=50)),
                ('administrador', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_contrato', models.CharField(choices=[('7X24', 'Contrato 7x24'), ('PREVENTIVO', 'Contrato Preventivo'), ('SIN_CONTRATO', 'Sin Contrato')], max_length=20)),
                ('frecuencia_lavado', models.IntegerField(choices=[(4, 'Cada 4 meses'), (6, 'Cada 6 meses')])),
                ('fecha_ultimo_lavado', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
