# Generated by Django 6.0.3 on 2026-03-04 00:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0002_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llamada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('descripcion_falla', models.TextField()),
                ('solucion_aplicada', models.TextField(blank=True, null=True)),
                ('horas_trabajadas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('es_nocturna', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('ATENDIDA', 'Atendida'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20)),
                ('aprobada_por_gerencia', models.BooleanField(default=False)),
                ('observaciones_internas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.cliente')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacion.tecnico')),
            ],
        ),
    ]
