# Generated by Django 6.0.3 on 2026-03-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0003_emergencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencia',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
