# Generated by Django 6.0.3 on 2026-03-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0004_emergencia_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencia',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10),
        ),
    ]
