# Generated by Django 6.0.3 on 2026-03-04 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0005_emergencia_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotacionTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_semana', models.DateField()),
                ('fecha_fin_semana', models.DateField()),
                ('es_fin_de_semana', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.tecnico')),
            ],
        ),
    ]
