# Generated by Django 6.0.3 on 2026-03-04 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0006_rotaciontecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='LavadoTanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('ejecutado', models.BooleanField(default=False)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('motivo_no_ejecucion', models.TextField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('publicado_cliente', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.cliente')),
            ],
            options={
                'ordering': ('-fecha_programada',),
                'unique_together': {('cliente', 'fecha_programada')},
            },
        ),
    ]
