# Generated by Django 6.0.3 on 2026-03-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0007_lavadotanque'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavadotanque',
            name='fecha_reprogramada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lavadotanque',
            name='motivo_reprogramacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lavadotanque',
            name='reprogramado',
            field=models.BooleanField(default=False),
        ),
    ]
