# Generated by Django 6.0.3 on 2026-03-05 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0008_lavadotanque_fecha_reprogramada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BOMBA_IMPULSION', 'Motobomba de impulsión'), ('BOMBA_PRESION', 'Motobomba de presión'), ('HIDROFLOW', 'Hidroflow'), ('TANQUE', 'Tanque'), ('TABLERO', 'Tablero eléctrico'), ('VALVULERIA', 'Válvulería'), ('OTRO', 'Otro (controlado)')], max_length=30)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('EN_REPARACION', 'En reparación')], default='OPERATIVO', max_length=20)),
                ('causa_fuera_servicio', models.TextField(blank=True, null=True)),
                ('ultima_revision', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='operacion.cliente')),
            ],
            options={
                'ordering': ('cliente__nombre', 'tipo'),
            },
        ),
        migrations.CreateModel(
            name='CotizacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NO_REQUIERE', 'No requiere'), ('PENDIENTE_ENVIO', 'Pendiente de envío'), ('ENVIADA', 'Enviada'), ('PENDIENTE_APROBACION', 'Pendiente de aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE_ENVIO', max_length=25)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='operacion.equipounidad')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
