# Generated by Django 6.0.3 on 2026-06-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0010_usuariocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipounidad',
            name='control',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='potencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='torre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='valor_comercial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='voltaje',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipounidad',
            name='tipo',
            field=models.CharField(choices=[('BOMBA_IMPULSION', 'Motobomba de impulsión'), ('BOMBA_PRESION', 'Motobomba de presión'), ('HIDROFLOW', 'Hidroflow'), ('TABLERO', 'Tablero eléctrico'), ('VALVULERIA', 'Válvulería'), ('OTRO', 'Otro')], max_length=30),
        ),
        migrations.CreateModel(
            name='DistribucionUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torre', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_pisos', models.PositiveIntegerField(blank=True, null=True)),
                ('presion_desde', models.PositiveIntegerField(blank=True, null=True)),
                ('presion_hasta', models.PositiveIntegerField(blank=True, null=True)),
                ('gravedad_desde', models.PositiveIntegerField(blank=True, null=True)),
                ('gravedad_hasta', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='operacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TanqueUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torre', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_tanque', models.CharField(choices=[('IMPULSION', 'Tanque de impulsión'), ('TERRAZA', 'Tanque de terraza'), ('HIDRONEUMATICO', 'Tanque hidroneumático'), ('OTRO', 'Otro')], max_length=30)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanques', to='operacion.cliente')),
            ],
        ),
    ]
