# Generated by Django 6.0.3 on 2026-07-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0011_equipounidad_control_equipounidad_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencia',
            name='persona_llama',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='recibido_por',
            field=models.CharField(blank=True, help_text='Coordinador o técnico de turno que recibió la llamada', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='telefono_llama',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='tipo_servicio',
            field=models.CharField(choices=[('EMERGENCIA', 'Emergencia'), ('CORRECTIVO', 'Correctivo'), ('GARANTIA', 'Garantía'), ('REVISION', 'Revisión')], default='CORRECTIVO', max_length=20),
        ),
    ]
