# Generated by Django 6.0.3 on 2026-07-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0012_emergencia_persona_llama_emergencia_recibido_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencia',
            name='cliente_conforme',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='materiales_usados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='numero_caso',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='observacion_cierre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='requiere_cotizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='requiere_regreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='resultado_servicio',
            field=models.CharField(blank=True, choices=[('OPERATIVO', 'Operativo'), ('OPERATIVO_PROVISIONAL', 'Operativo provisional'), ('PENDIENTE_REPUESTO', 'Pendiente repuesto'), ('REQUIERE_COTIZACION', 'Requiere cotización'), ('REQUIERE_REGRESO', 'Requiere regreso'), ('NO_SOLUCIONADO', 'No solucionado')], max_length=30, null=True),
        ),
    ]
