# Generated by Django 6.0.3 on 2026-07-03 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0013_emergencia_cliente_conforme_emergencia_diagnostico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('icono', models.CharField(default='📌', max_length=20)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='operacion.emergencia')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
