# Generated by Django 6.0.3 on 2026-07-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0014_eventoservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipounidad',
            name='anio_fabricacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='codigo_activo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='fecha_levantamiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='informacion_validada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='nombre_equipo',
            field=models.CharField(blank=True, help_text='Ejemplo: Bomba de presión No. 2', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='equipounidad',
            name='placa_identificada',
            field=models.BooleanField(default=False),
        ),
    ]
