# Generated by Django 6.0.3 on 2026-07-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0015_equipounidad_anio_fabricacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='operacion.cliente')),
                ('usuario_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asignados', to='operacion.usuariocliente')),
            ],
            options={
                'ordering': ['-principal', 'cliente__nombre'],
                'unique_together': {('usuario_cliente', 'cliente')},
            },
        ),
    ]
