# Generated by Django 6.0.3 on 2026-08-05 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0016_clienteasignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('ACTIVIDAD_TECNICA', 'Actividad técnica'), ('LLAMADA_CLIENTE', 'Llamada de cliente'), ('REUNION', 'Reunión'), ('REGRESO', 'Regreso a unidad'), ('COTIZACION', 'Cotización pendiente'), ('COMPROMISO', 'Compromiso'), ('MATERIAL', 'Material o repuesto pendiente'), ('ENTREGA_TURNO', 'Entrega de turno'), ('NOTA_INTERNA', 'Nota interna'), ('OTRO', 'Otro')], default='NOTA_INTERNA', max_length=30)),
                ('descripcion', models.TextField()),
                ('accion_pendiente', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_SEGUIMIENTO', 'En seguimiento'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20)),
                ('fecha_compromiso', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('visible_cliente', models.BooleanField(default=False, help_text='Permite mostrar esta novedad en el portal del cliente.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='operacion.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_creadas', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_asignadas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='operacion.emergencia')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='operacion.tecnico')),
            ],
            options={
                'verbose_name': 'Bitácora operativa',
                'verbose_name_plural': 'Bitácoras operativas',
                'ordering': ('estado', '-prioridad', 'fecha_compromiso', '-creado'),
            },
        ),
    ]
