# Generated by Django 6.0.3 on 2026-08-12 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0017_bitacoraoperativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemisionTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_remision', models.CharField(max_length=50, unique=True, verbose_name='Número de remisión física')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de conciliar'), ('CONCILIADA', 'Conciliada')], default='PENDIENTE', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remisiones_tecnicas', to='operacion.cliente')),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_entregadas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(blank=True, help_text='Caso 7x24 relacionado, si existe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones', to='operacion.emergencia')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remisiones', to='operacion.tecnico')),
            ],
            options={
                'verbose_name': 'Remisión de técnico',
                'verbose_name_plural': 'Remisiones de técnicos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_accesorio', models.CharField(blank=True, max_length=50)),
                ('descripcion_accesorio', models.CharField(max_length=250)),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_devuelta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operacion.remisiontecnico')),
            ],
        ),
    ]
