# Generated by Django 6.0.3 on 2026-08-13 15:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0018_remisiontecnico_detalleremision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('CORRECTIVO', 'Correctivo'), ('DIAGNOSTICO', 'Visita de diagnóstico'), ('REGRESO', 'Regreso a unidad'), ('GARANTIA', 'Garantía'), ('PREVENTIVO', 'Mantenimiento preventivo'), ('INSTALACION', 'Instalación'), ('OTRO', 'Otro')], default='CORRECTIVO', max_length=30)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('labor_realizada', models.TextField()),
                ('resultado', models.CharField(blank=True, choices=[('OPERATIVO', 'Equipo operativo'), ('OPERATIVO_PROVISIONAL', 'Operativo provisional'), ('PENDIENTE_REPUESTO', 'Pendiente repuesto'), ('REQUIERE_COTIZACION', 'Requiere cotización'), ('REQUIERE_REGRESO', 'Requiere regreso'), ('NO_SOLUCIONADO', 'No solucionado')], max_length=30, null=True)),
                ('requiere_regreso', models.BooleanField(default=False)),
                ('requiere_cotizacion', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_tecnicas', to='operacion.cliente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_tecnicas_registradas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_tecnicas', to='operacion.emergencia')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='operacion.tecnico')),
            ],
            options={
                'verbose_name': 'Actividad de técnico',
                'verbose_name_plural': 'Actividades de técnicos',
                'ordering': ['-fecha', '-hora_inicio', '-id'],
            },
        ),
    ]
