# Generated by Django 6.0.3 on 2026-08-13 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0019_actividadtecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadtecnico',
            name='remision',
            field=models.ForeignKey(blank=True, help_text='Remisión de accesorios relacionada con esta actividad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='operacion.remisiontecnico'),
        ),
    ]
