# Generated by Django 6.0.3 on 2026-08-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0020_actividadtecnico_remision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividadtecnico',
            old_name='hora_inicio',
            new_name='hora_llegada',
        ),
        migrations.RemoveField(
            model_name='actividadtecnico',
            name='hora_fin',
        ),
        migrations.AlterField(
            model_name='actividadtecnico',
            name='hora_llegada',
            field=models.TimeField(
                blank=True,
                null=True,
                verbose_name='Hora de llegada a la unidad',
            ),
        ),
        migrations.AlterField(
            model_name='actividadtecnico',
            name='hora_salida',
            field=models.TimeField(
                blank=True,
                null=True,
                verbose_name='Hora de salida de la unidad',
            ),
        ),
        migrations.AlterModelOptions(
            name='actividadtecnico',
            options={
                'ordering': ['-fecha', '-hora_llegada', '-id'],
                'verbose_name': 'Actividad de técnico',
                'verbose_name_plural': 'Actividades de técnicos',
            },
        ),
    ]
