# Generated by Django 6.0.3 on 2026-08-16 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0021_alter_actividadtecnico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorios',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='AccesorioActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_otro', models.BooleanField(default=False)),
                ('descripcion_otro', models.CharField(blank=True, max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('observacion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('accesorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_actividades', to='operacion.accesorio')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesorios_utilizados', to='operacion.actividadtecnico')),
            ],
            options={
                'verbose_name': 'Accesorio utilizado',
                'verbose_name_plural': 'Accesorios utilizados',
                'ordering': ['id'],
            },
        ),
    ]
