# Generated by Django 6.0.3 on 2026-08-16 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0022_accesorio_accesorioactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraoperativa',
            name='actividad',
            field=models.ForeignKey(blank=True, help_text='Actividad realizada por el técnico relacionada con esta novedad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='operacion.actividadtecnico', verbose_name='Actividad técnica relacionada'),
        ),
    ]
