# Generated by Django 6.0.3 on 2026-08-20 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0023_bitacoraoperativa_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso'),
        ),
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_nivel', models.TextField(blank=True)),
                ('tablero_electrico', models.TextField(blank=True)),
                ('novedades', models.TextField(blank=True)),
                ('persona_recibe', models.CharField(blank=True, max_length=150)),
                ('cargo_recibe', models.CharField(blank=True, max_length=120)),
                ('firma_recibido', models.FileField(blank=True, null=True, upload_to='preventivos/firmas/%Y/%m/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preventivo', to='operacion.actividadtecnico')),
            ],
            options={
                'verbose_name': 'Mantenimiento preventivo',
                'verbose_name_plural': 'Mantenimientos preventivos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='MedicionEquipoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(blank=True, help_text='Nombre guardado como referencia histórica.', max_length=180)),
                ('voltaje_medido', models.CharField(blank=True, max_length=50)),
                ('corriente_medida', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('CON_NOVEDAD', 'Operativo con novedad'), ('FUERA_SERVICIO', 'Fuera de servicio'), ('NO_REVISADO', 'No revisado')], default='OPERATIVO', max_length=25)),
                ('observaciones', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones_preventivas', to='operacion.equipounidad')),
                ('preventivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_equipos', to='operacion.mantenimientopreventivo')),
            ],
            options={
                'verbose_name': 'Medición de equipo en preventivo',
                'verbose_name_plural': 'Mediciones de equipos en preventivos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RevisionComponentePreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VALVULA', 'Válvula'), ('CHEQUE', 'Cheque'), ('FLOTADOR', 'Flotador mecánico'), ('PRESOSTATO', 'Presostato'), ('MANOMETRO', 'Manómetro'), ('OTRO', 'Otro')], max_length=30)),
                ('estado', models.CharField(choices=[('OK', 'Funciona correctamente'), ('CON_NOVEDAD', 'Presenta novedad'), ('REQUIERE_CAMBIO', 'Requiere cambio'), ('NO_APLICA', 'No aplica')], default='OK', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('preventivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_revisados', to='operacion.mantenimientopreventivo')),
            ],
            options={
                'verbose_name': 'Componente revisado en preventivo',
                'verbose_name_plural': 'Componentes revisados en preventivos',
                'ordering': ['tipo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RevisionTanquePreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tanque', models.CharField(blank=True, help_text='Descripción guardada como referencia histórica.', max_length=180)),
                ('capacidad', models.CharField(blank=True, max_length=100)),
                ('precarga_aire', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('preventivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanques_revisados', to='operacion.mantenimientopreventivo')),
                ('tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_preventivas', to='operacion.tanqueunidad')),
            ],
            options={
                'verbose_name': 'Revisión de tanque en preventivo',
                'verbose_name_plural': 'Revisiones de tanques en preventivos',
                'ordering': ['id'],
            },
        ),
    ]
