# Generated by Django 6.0.3 on 2026-08-20 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0024_tecnico_user_mantenimientopreventivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionMantenimientoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('hora_programada', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En proceso'), ('EJECUTADO', 'Ejecutado'), ('REPROGRAMADO', 'Reprogramado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_reprogramada', models.DateField(blank=True, null=True)),
                ('motivo_reprogramacion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actividad', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacion_preventiva', to='operacion.actividadtecnico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preventivos_programados', to='operacion.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventivos_programados_creados', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preventivos_programados', to='operacion.tecnico')),
            ],
            options={
                'verbose_name': 'Programación de mantenimiento preventivo',
                'verbose_name_plural': 'Programaciones de mantenimientos preventivos',
                'ordering': ['fecha_programada', 'hora_programada', 'id'],
            },
        ),
    ]
