# Generated by Django 6.0.3 on 2026-08-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0025_programacionmantenimientopreventivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Administración',
                'verbose_name_plural': 'Administraciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AdministracionUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_asignadas', to='operacion.administracion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_administraciones', to='operacion.cliente')),
            ],
            options={
                'verbose_name': 'Administración de unidad',
                'verbose_name_plural': 'Administraciones de unidades',
                'ordering': ['-activo', '-fecha_inicio'],
            },
        ),
    ]
