# Generated by Django 6.0.3 on 2026-08-25 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0026_administracion_administracionunidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAdministracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('administracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='operacion.administracion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_administracion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
