# Generated by Django 6.0.3 on 2026-09-01 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0027_usuarioadministracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ContratoPase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pase', models.CharField(max_length=30, unique=True)),
                ('nombre_servicio', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('7X24', 'Contrato 7x24'), ('PREVENTIVO', 'Contrato preventivo'), ('OTRO', 'Otro')], default='PREVENTIVO', max_length=20)),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=14)),
                ('periodicidad', models.CharField(choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('CUATRIMESTRAL', 'Cada 4 meses')], max_length=20)),
                ('estado_valor', models.CharField(choices=[('PROVISIONAL', 'Provisional'), ('DEFINITIVO', 'Definitivo'), ('PENDIENTE_ACTUALIZACION', 'Pendiente de actualizacion')], default='DEFINITIVO', max_length=30)),
                ('direccion_servicio', models.CharField(blank=True, max_length=250)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_inicio_facturacion', models.DateField(blank=True, null=True)),
                ('dia_limite_facturacion', models.PositiveSmallIntegerField(default=15)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_pases', to='operacion.cliente')),
            ],
            options={
                'verbose_name': 'Contrato o pase',
                'verbose_name_plural': 'Contratos o pases',
                'ordering': ['cliente__nombre', 'numero_pase'],
            },
        ),
    ]
