# Generated by Django 6.0.3 on 2026-09-02 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0028_cliente_nit_contratopase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturacionPase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer dia del mes que corresponde facturar.')),
                ('fecha_limite', models.DateField()),
                ('valor_programado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('POR_CONFIRMAR', 'Por confirmar en Siigo'), ('PENDIENTE', 'Pendiente'), ('FACTURADA', 'Facturada'), ('APLAZADA', 'Aplazada'), ('NO_FACTURAR', 'No facturar')], default='PENDIENTE', max_length=25)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('fecha_factura', models.DateField(blank=True, null=True)),
                ('valor_facturado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturaciones', to='operacion.contratopase')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturaciones_pases_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facturacion de pase',
                'verbose_name_plural': 'Facturaciones de pases',
                'ordering': ['periodo', 'contrato__cliente__nombre'],
                'indexes': [models.Index(fields=['periodo', 'estado'], name='operacion_f_periodo_56ff73_idx')],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'periodo'), name='facturacion_unica_por_pase_periodo')],
            },
        ),
    ]
