# Generated by Django 6.0.3 on 2026-09-04 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0029_facturacionpase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_nombre', models.CharField(editable=False, max_length=254)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('COMENTARIO', 'Seguimiento'), ('EDICION', 'Cambio de datos')], default='COMENTARIO', editable=False, max_length=12)),
                ('comentario', models.TextField(blank=True, editable=False)),
                ('cambios', models.JSONField(blank=True, default=list, editable=False)),
                ('solicitud', models.UUIDField(editable=False, null=True, unique=True)),
                ('autor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_bitacora', to=settings.AUTH_USER_MODEL)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='operacion.bitacoraoperativa')),
            ],
            options={
                'verbose_name': 'Seguimiento de bitácora',
                'verbose_name_plural': 'Seguimientos de bitácora',
                'ordering': ('-creado', '-pk'),
            },
        ),
    ]
