# Generated by Django 6.0.3 on 2026-09-04 02:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0030_seguimiento_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientobitacora',
            name='tipo',
            field=models.CharField(choices=[('COMENTARIO', 'Seguimiento'), ('EDICION', 'Cambio de datos'), ('ADJUNTO', 'Archivo adjunto')], default='COMENTARIO', editable=False, max_length=12),
        ),
        migrations.CreateModel(
            name='AdjuntoBitacora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_original', models.CharField(editable=False, max_length=200)),
                ('ruta_privada', models.CharField(editable=False, max_length=200)),
                ('tamano', models.PositiveBigIntegerField(editable=False)),
                ('tipo_mime', models.CharField(editable=False, max_length=100)),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('seguimiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adjunto', to='operacion.seguimientobitacora')),
            ],
            options={
                'verbose_name': 'Adjunto de bitácora',
                'verbose_name_plural': 'Adjuntos de bitácora',
                'ordering': ('-seguimiento__creado',),
            },
        ),
    ]
