# Generated by Django 5.2.15 on 2026-09-04 16:59

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0031_adjunto_bitacora'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sectores', to='operacion.cliente')),
            ],
            options={
                'verbose_name': 'Sector del cliente',
                'verbose_name_plural': 'Sectores de clientes',
                'ordering': ('cliente__nombre', 'nombre', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='bitacoraoperativa',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras', to='operacion.sectorcliente'),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='operacion.sectorcliente'),
        ),
        migrations.AddConstraint(
            model_name='sectorcliente',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('nombre')), models.F('cliente'), name='sector_cliente_nombre_unico'),
        ),
    ]
