# Generated by Django 5.2.15 on 2026-09-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0032_sectores_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraoperativa',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_SEGUIMIENTO', 'En seguimiento'), ('CERRADO', 'Cerrado'), ('IMPORTADO', 'Importado / por revisar')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='OrigenNotaKeep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('huella_texto', models.CharField(max_length=64)),
                ('fecha_original', models.DateField()),
                ('referencia_original', models.CharField(max_length=200)),
                ('archivo_original', models.CharField(max_length=500)),
                ('texto_original', models.TextField()),
                ('nota_original', models.JSONField()),
                ('posiciones', models.JSONField()),
                ('vinculo_importado', models.JSONField()),
                ('lote_sha256', models.CharField(max_length=64)),
                ('importado', models.DateTimeField(auto_now_add=True)),
                ('bitacora', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='origen_keep', to='operacion.bitacoraoperativa')),
            ],
            options={
                'verbose_name': 'Origen de nota Keep',
                'verbose_name_plural': 'Orígenes de notas Keep',
                'ordering': ('fecha_original', 'pk'),
            },
        ),
    ]
