# Generated by Django 6.0.3 on 2026-08-09 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacion', '0017_bitacoraoperativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción / concepto')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'Pendiente de revisión'), ('DEVUELTA', 'Devuelta para corrección'), ('APROBADA', 'Aprobada'), ('LISTA_FACTURAR', 'Lista para facturar'), ('FACTURADA', 'Facturada'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=20)),
                ('subtotal_materiales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('horas_adicionales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transporte', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('otros_costos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_sin_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones_revision', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_facturacion', models.DateTimeField(blank=True, null=True)),
                ('numero_factura', models.CharField(blank=True, help_text='Número de factura generado posteriormente en SIIGO.', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_comerciales', to='operacion.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación comercial',
                'verbose_name_plural': 'Liquidaciones comerciales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
