# Generated by Django 6.0.3 on 2026-08-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(max_length=250, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Catálogo de precios',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TarifaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HORA_NORMAL', 'Hora normal'), ('HORA_NOCTURNA', 'Hora nocturna'), ('SABADO', 'Sábado'), ('DOMINGO_FESTIVO', 'Domingo / Festivo'), ('AUXILIO', 'Auxilio'), ('TRANSPORTE', 'Transporte'), ('OTRO', 'Otro')], max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tarifa operativa',
                'verbose_name_plural': 'Tarifas operativas',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MATERIAL', 'Material / accesorio'), ('MANO_OBRA', 'Mano de obra'), ('HORA_ADICIONAL', 'Hora adicional'), ('TRANSPORTE', 'Transporte'), ('AUXILIO', 'Auxilio'), ('OTRO', 'Otro costo')], max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion_comercial.liquidacion')),
            ],
        ),
    ]
