# Generated by Django 6.0.3 on 2026-08-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_comercial', '0002_catalogoprecio_tarifaoperativa_detalleliquidacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoprecio',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
