# Generated by Django 6.0.3 on 2026-08-10 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_comercial', '0003_alter_catalogoprecio_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleliquidacion',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_liquidacion', to='gestion_comercial.catalogoprecio', verbose_name='Accesorio del catálogo'),
        ),
    ]
