# Generated by Django 6.0.3 on 2026-08-16 22:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_comercial', '0004_detalleliquidacion_catalogo'),
        ('operacion', '0023_bitacoraoperativa_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('UNIDAD_NUEVA', 'Unidad nueva'), ('SOLICITUD_CLIENTE', 'Solicitud del cliente'), ('ACTIVIDAD_TECNICA', 'Actividad técnica'), ('CASO_7X24', 'Caso 7x24'), ('OTRO', 'Otro')], db_index=True, default='SOLICITUD_CLIENTE', max_length=30)),
                ('asunto', models.CharField(max_length=250, verbose_name='Asunto / concepto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ELABORADA', 'Elaborada'), ('ENVIADA', 'Enviada al cliente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=20)),
                ('valor_sin_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='operacion.actividadtecnico')),
                ('bitacora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='operacion.bitacoraoperativa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='operacion.cliente')),
                ('elaborado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_elaboradas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='operacion.emergencia')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='gestion_comercial.catalogoprecio', verbose_name='Artículo del catálogo')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion_comercial.cotizacion')),
            ],
        ),
    ]
