# Generated by Django 6.0.3 on 2026-08-17 01:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_comercial', '0005_cotizacion_detallecotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='porcentaje_utilidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Utilidad (%)'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal_costos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='valor_utilidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='tipo',
            field=models.CharField(choices=[('MATERIAL', 'Material / accesorio'), ('MANO_OBRA', 'Mano de obra'), ('HORA_ADICIONAL', 'Hora adicional'), ('TRANSPORTE', 'Transporte'), ('AUXILIO', 'Auxilio'), ('OTRO', 'Otro concepto')], default='MATERIAL', max_length=20),
        ),
    ]
