# Generated by Django 6.0.3 on 2026-08-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_comercial', '0006_cotizacion_porcentaje_utilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.TextField(blank=True, help_text='Ej.: 50% anticipo y 50% contra entrega.', verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(blank=True, help_text='Se genera automáticamente, por ejemplo COT-2026-0003.', max_length=30, null=True, unique=True, verbose_name='Número de cotización'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vigencia_dias',
            field=models.PositiveIntegerField(default=30, verbose_name='Validez de la oferta (días)'),
        ),
    ]
