# Generated by Django 6.0.3 on 2026-08-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_comercial', '0007_cotizacion_forma_pago_cotizacion_numero_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='alcance_tecnico',
            field=models.TextField(blank=True, verbose_name='Alcance técnico'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='concepto_comercial',
            field=models.TextField(blank=True, verbose_name='Concepto comercial'),
        ),
    ]
