# Generated by Django 6.0.3 on 2026-08-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_comercial', '0008_cotizacion_alcance_tecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión'),
        ),
    ]
