# Generated by Django 6.0.3 on 2026-08-28 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_comercial', '0010_cotizacion_aprobado_por_cotizacion_fecha_aprobacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='cotizaciones/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='gestion_comercial.cotizacion')),
            ],
            options={
                'verbose_name': 'Imagen de cotización',
                'verbose_name_plural': 'Imágenes de cotización',
                'ordering': ['fecha_carga'],
            },
        ),
    ]
