# Generated by Django 6.0.3 on 2026-08-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_comercial', '0011_imagencotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ELABORADA', 'Elaborada'), ('LISTA_ENVIAR', 'Lista para enviar al cliente'), ('ENVIADA', 'Enviada al cliente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada')], db_index=True, default='BORRADOR', max_length=20),
        ),
    ]
